version: '3.1'

services:
  db:
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root@123
    ports:
          - 3306:3306

  adminer:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USERNAME: root
      PMA_PASSWORD: root@123
    ports:
      - 8090:80
    depends_on:
      - db
      
      
